### ISSUE TITLE
General: Phone number area code doesn't match from the area code of the header and the footer section which is only 2 digit

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Chamberlains#13]
![image](https://cloud.githubusercontent.com/assets/13363508/10839074/0e53c004-7f0a-11e5-92d8-8b849b181314.png)

**Comment by maehtitan** [comment]
@saif-titan still the area code is 3 digits

**Comment by saif-titan** [comment]
@maehtitan Please hard refresh the pages. because on my side its showing only 2 digits and I've tested with all devices.

**Comment by maehtitan** [comment]
![image](https://cloud.githubusercontent.com/assets/13363508/11138539/8c12ff1a-89fe-11e5-9dd6-9f16903f2379.png)
![image](https://cloud.githubusercontent.com/assets/13363508/11138544/97abe13e-89fe-11e5-8e92-8b1eebb49293.png)

<b> Please strip the open and close parenthesis to make it all consistent.

**Comment by saif-titan** [comment]
![d33d6c15-04b9-43cb-9954-b8501cf687d5](https://cloud.githubusercontent.com/assets/13676221/11232744/35a853bc-8d6b-11e5-88e3-7ed69dd8fc1c.jpg)

**Comment by saif-titan** [comment]
Please try clearing the cache and test again because my side its working fine.

**Comment by maehtitan** [comment]
If that is completely fixed, why is that we can still replicate in itouch and iPad, and fixed in Android phones only
![image](https://cloud.githubusercontent.com/assets/13363508/11265529/d7d28af0-8ed7-11e5-97d4-2bb8fa94c500.png)
![image](https://cloud.githubusercontent.com/assets/13363508/11265544/ed22aeb2-8ed7-11e5-93a9-0c5c875d2275.png)

**Comment by saif-titan** [comment]
This is the comment by Bernard. Please refer
kindly mark that one down as won'tfix as it's a device issue.
