### ISSUE TITLE
Products Single View: Why there is a "Blurb Information coming soon."  under Starter Motors, Air Conditioning and Auto Electrics pages?

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Chamberlains#22]

**Comment by saif-titan** [comment]
ACF has been created with name Product/Service blurb and we can manage from here http://chamberlainautoelectrics.stage.titanweb.com.au/wp-admin/post.php?post=111&action=edit

**Comment by maehtitan** [comment]
@saif-titan Oh I see. Thanks
