### ISSUE TITLE
Stretched images: Found a lot of stretched images

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Chamberlains#32]
<b>Homepage: S4 & Itouch ( portrait)
![image](https://cloud.githubusercontent.com/assets/13363508/11024570/28450810-86cb-11e5-9658-c7383ed9c336.png)
<b>Homepage: S4 & Itouch ( landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/11024573/2ed611c4-86cb-11e5-82e5-48241a195a9e.png)
<b>Employment: S4 & Itouch (portrait & landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/11024609/d6a2fe30-86cb-11e5-81ed-8fab2f52305b.png)
![image](https://cloud.githubusercontent.com/assets/13363508/11024654/87aa965c-86cc-11e5-8d12-d7d398b6c9bf.png)
<b>Services: Mobile Car Electricians: S4 & Itouch (portrait & landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/11024667/cc969356-86cc-11e5-88ca-050ee3b423f5.png)
![image](https://cloud.githubusercontent.com/assets/13363508/11024674/e1160276-86cc-11e5-8ae6-9f79e6ba886e.png)
Products: S4 & Itouch (portrait & landscape) - Batteries Image is not view completely in thumbnail which some edges(top & bottom) are cut
![image](https://cloud.githubusercontent.com/assets/13363508/11024695/5ba662e2-86cd-11e5-9513-f4e6ff15e2ee.png)

**Comment by saif-titan** [comment]
If the images are still streched. Please upload the big size images.

**Comment by maehtitan** [comment]
It is the actual image of the products & the pages it really needs to retain the quality of the image
