### ISSUE TITLE
Gallery: There is a missing image in S4 device and there is a black and white image in desktop view

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Chamberlains#38]
Device: S4 (landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/11266641/e7326110-8ee0-11e5-986c-638e24456c62.png)

Desktop:
![image](https://cloud.githubusercontent.com/assets/13363508/11266625/ce235a76-8ee0-11e5-85eb-fcb3b4a7e154.png)

**Comment by maehtitan** [comment]
S4 is fixed but in Desktop still black half and white half of the image

**Comment by saif-titan** [comment]
![gallery - chamberlain auto electrics 2015-11-26 08-48-09](https://cloud.githubusercontent.com/assets/13676221/11401004/53bc925c-9345-11e5-8d56-22de496b31db.png)

please clear the browser caches .
